const BAD_DATA = 400;
const DOC_NOTFOUND_ERROR = 404;
const DEFAULT_ERROR = 500;
const DUPLICATE_ERROR = 409;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;

module.exports = {
  BAD_DATA,
  DOC_NOTFOUND_ERROR,
  DEFAULT_ERROR,
  DUPLICATE_ERROR,
  UNAUTHORIZED,
  FORBIDDEN,
};
